### ISSUE TITLE
图标还是没有替换啊！

### ISSUE THREAD

**Issue by xiezy1** [PromiseAll/pkg-exe-build#1]
hello 啊！
我这边测试还是不行，nodejs版本是16.13.2 pkg打包的版本是nodejs12-win-x64，
版本信息之类的都没修改。exeBuild.config.js是在根目录下的

目录结构
---dist
     --- name.exe
---node_modeuls
---app.ico
---index.js
---exeBuild.config.js
---package.json
---package-lock.json

**Comment by PromiseAll** [comment]
能看一下你的配置文件嘛？

**Comment by PromiseAll** [comment]
```cmd
> Download Binaries
  fetched-v12.22.11-win-x64           [====================] 100%

> Read EXE
> Set Product Version
> Set File Version
> Set File Info
> Set Icon
> Generate EXE
> Save EXE
> Bundling App
> pkg@5.7.0
> Reusing base binaries built locally:
  C:\Users\Promise\.pkg-cache\v3.4\built-v12.22.11-win-x64
````
我node 版本 16.15.1 当前测试["node12-win-x64"]是可以修改的

**Comment by PromiseAll** [comment]
![image](https://user-images.githubusercontent.com/56338627/176817217-1617f29b-1a09-4851-8082-ee1be6751c4b.png)

**Comment by xiezy1** [comment]
可以哈！我也不知道什么问题，我今天又试了一下，可以了。蟹蟹

**Comment by xiezy1** [comment]
！
