### ISSUE TITLE
i can't build it for linux

### ISSUE THREAD

**Issue by Eva-Skye** [PromiseAll/pkg-exe-build#3]
something wrong

**Comment by PromiseAll** [comment]
> something wrong

 有什么报错信息吗 ?

**Comment by Eva-Skye** [comment]
原来是中国人哈哈哈，我还在绞尽脑汁怎么搞翻译，那麻烦大佬帮看看噢。
![image](https://user-images.githubusercontent.com/45868259/235405722-9afb8398-aeba-4f94-8bc7-cf8cab305772.png)

**Comment by Eva-Skye** [comment]
还有一个报错是这样的
![image](https://user-images.githubusercontent.com/45868259/235405893-8a114837-969f-4525-84be-c9c0d31df05a.png)

我使用原本的pkg指令来打包就可以

**Comment by PromiseAll** [comment]
> 还有一个报错是这样的
> ![image](https://user-images.githubusercontent.com/45868259/235405893-8a114837-969f-4525-84be-c9c0d31df05a.png)
> 
> 我使用原本的pkg指令来打包就可以

 啊哈没注意看问题 ，这个包的目的主要是为了win打包时 可以替换exe软件的图标 ，目前只能打包win平台的，不支持 linux哦，打包linux的话使用使用原来的pkg

**Comment by Eva-Skye** [comment]
原来如此，我还发现一个现象噢，使用这个打包后包的体积是使用pkg的二分之一，这正常吗，我测试了一下命令暂时没发现什么问题，为什么体积会缩小那么多呢？



---Original---
From: ***@***.***&gt;
Date: Mon, May 1, 2023 12:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [PromiseAll/pkg-exe-build] i can't build it for linux (Issue #3)




  
还有一个报错是这样的
 
 
我使用原本的pkg指令来打包就可以
  
啊哈没注意看问题 ，这个包的目的主要是为了win打包时 可以替换exe软件的图标 ，目前只能打包win平台的，不支持 linux哦，打包linux的话使用使用原来的pkg

**Comment by PromiseAll** [comment]
> 原来如此，我还发现一个现象噢，使用这个打包后包的体积是使用pkg的二分之一，这正常吗，我测试了一下命令暂时没发现什么问题，为什么体积会缩小那么多呢？
> 
> 
> 
> ---Original---
> From: ***@***.***&gt;
> Date: Mon, May 1, 2023 12:34 PM
> To: ***@***.***&gt;;
> Cc: ***@***.******@***.***&gt;;
> Subject: Re: [PromiseAll/pkg-exe-build] i can't build it for linux (Issue #3)
> 
> 
> 
> 
>   
> 还有一个报错是这样的
>  
>  
> 我使用原本的pkg指令来打包就可以
>   
> 啊哈没注意看问题 ，这个包的目的主要是为了win打包时 可以替换exe软件的图标 ，目前只能打包win平台的，不支持 linux哦，打包linux的话使用使用原来的pkg
>  
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

因为使用了压缩指令，你看pkg官方文档有的
